### ISSUE TITLE
Road To 3.0

### ISSUE THREAD

**Issue by mbabker** [BabDev/Pagerfanta#1]
The 2.2 release here is an update from the original package's last release (2.1.3) which was mostly code style adjustments, deprecating some adapters, and a PHP minimum version update.

A 3.0 version of this package will start soon.  Some changes I am thinking about include:

- Removing deprecated elements
- PHP 7.4 minimum
- Strongly typed API
- Extracting the Doctrine, Elastica, and Solarium adapters into separate packages
    - The rationale here is it should be possible to add new "officially supported" adapters, deprecate adapters, and update adapters based on their upstream changes without forcing version updates of the base Pagerfanta API
    - Yet to be determined is how to deal with class naming (keep class names as is or rename when moved to an external package (such as `Pagerfanta\Solarium\SolariumAdapter` or `Pagerfanta\DoctrineCollections\CollectionsAdapter`))

The release timeframe on this is most likely going to match up with the release timeframe for the BabDevPagerfantaBundle 3.0 release, which will come around the time Symfony 3.4 stops receiving regular bug fixes (November 2020).

The intent for this release isn't to rewrite everything for the sake of rewriting, but rather to upgrade the code structure to reflect the modern version of PHP we have now versus the version that existed when the library was first written, and to also give more flexibility to the release patterns of the adapters.

**Comment by stof** [comment]
Do you plan to maintain adapters as a monorepo with read-only subtree splits for composer packages, or directly in separate repos ?

Also, splitting adapters into their own repos means that you might end up having many repos:

- pagerfanta core
- PagerfantaBundle
- Doctrine Collections adapter
- Doctrine DBAL adapter
- Doctrine ORM adapter
- Doctrine MongoDB ODM adapter
- Doctrine PHPCR ODM adapter
- Elastica adapter
- Solarium adapter
- ~Mandango adapter~
- ~Mongo adapter~ (but might be replaced by a MongoDB one using the new extension instead)
- ~Propel adapter~
- ~Propel2 adapter~

It might make sense to create a dedicated github organization to hold all these repos

**Comment by mbabker** [comment]
Hadn't thought that part out yet in all honesty.

https://github.com/pagerfanta is already claimed otherwise I'd just move the repos there.  I guess a "pagerfanta-readonly" org that is nothing but subsplit repos could work here if doing monorepo since the subsplits don't need to be as easily discovered (loosely similar to how https://github.com/laravel is all the collaborative repos and https://github.com/illuminate is the read-only subsplits of the main framework).

> ~Mongo adapter~ (but might be replaced by a MongoDB one using the new extension instead)

I've never done any work with MongoDB so if someone wants to help with that or fixing the Doctrine adapter's test (looks like it was written for 1.x but the tests as written won't fly on 2.x due to final classes), it'd be greatly appreciated.

**Comment by stof** [comment]
@dongasai it looks like you were the one creating the https://github.com/pagerfanta organization and forking Pagerfanta there, but without going further on working on them. Do you have any plan for it, or could it be transferred to @mbabker ?
