### ISSUE TITLE
Stable release ruflin/elastica 7

### ISSUE THREAD

**Issue by MaximGns** [BabDev/Pagerfanta#11]
I saw that ruflin/elastica has a new stable release for ES7. Do you look into supporting this version? Kind regards

**Comment by mbabker** [comment]
Since there aren't any version constraints on the package dependency (the dev dependencies don't affect people's installations in their apps), it should work just fine unless they finally made a B/C breaking change.

**Comment by mbabker** [comment]
Just added it to the list of versions to test, it passes fine so should work.

If you do find a bug with it though, feel free to open an issue with details about that bug.
