### ISSUE TITLE
Pagerfanta\Exception\Exception triggers deprecation log on every request

### ISSUE THREAD

**Issue by kevinpapst** [BabDev/Pagerfanta#25]
This is a duplicate of #13 but I want to re-open it, because this is a regression in my eyes.

I am seeing 
```
Since pagerfanta/pagerfanta 2.2: The "Pagerfanta\Exception\Exception" interface is deprecated and will be removed in 3.0, exceptions should implement "Pagerfanta\Exception\PagerfantaException" instead
```

Updating to 3.0 is not a solution for quite a while, because of the 7.4 requirement and going back to a release that did not include the deprecation feels wrong too.

Can we work on fixing/removing the deprecation? Probably marking the interface as internal instead?
You are triggering a deprecation without any user land implementation. I is triggered simply by using pagerfanta.
I understand the reason why you did that, but this feels wrong to me. 
Now a deprecation is triggered on every page load of every project out there that uses pagerfanta 2.x.

**Comment by mbabker** [comment]
The sanest option that exists would be to flat out remove the `@deprecated` annotation and the runtime trigger.  Otherwise, Symfony's debug handling is going to log a deprecation that you can't fix.  FWIW, Symfony's debug class loader processes `@final`, `@deprecated`, and `@internal` annotations on a class, so using any of those will end up in something being logged somewhere.

I don't think it's right to remove any part of the API without some kind of communication that it's a deprecated element, so one of those has to stay there; it's a really poor management strategy to rely purely on having people read a changelog or upgrade file for them to realize "oh, this was deprecated".

So I'm kind of left between a rock and a hard place.  Either I remove all deprecation notices from the 2.x branch so something like Symfony's ErrorHandler component doesn't create noise at the expense of developers never receiving a notification that a deprecated element is used (be it runtime logging or your IDE highlighting something), or I leave them in and I have issues like this one come up.

**Comment by kevinpapst** [comment]
I am running SF 4.4 and when I remove the `trigger_deprecation` call there is no log showing up. And I left the `@deprecated` as is. 

I totally get your point, but in my view this is wrong usage of a deprecation. It is triggered on every single page load, no matter what is executed and even without any pagerfanta code used.

Maybe this discussion is a bit too late, as v3 is already released, but why did you deprecate the class in the first place? 
Just to have a different name?

**Comment by mbabker** [comment]
Out of curiosity, can you get a stack trace or something that shows when the file gets loaded?  The only reason I can think of the deprecation being logged on every request is something is causing the file to be loaded no matter what (like Symfony's preloader for PHP 7.4 perhaps?).  Beyond that, I wouldn't expect any of the exception class files to be loaded until an exception is thrown, so really only requests that trigger an exception inside Pagerfanta should get the deprecation logged, but I wouldn't write off something else I'm not thinking of causing it either.

**Comment by kevinpapst** [comment]
Okay, now I feel a bit stupid 😊 My assumptions were at least partially wrong. 
I haven't debugged that in full detail, but what I found out by now:

I registered `Pagerfanta\Exception\OutOfRangeCurrentPageException` for Exception mapping inside my FOSRest API:
```yaml
fos_rest:
    exception:
        codes:
            'Pagerfanta\Exception\OutOfRangeCurrentPageException': 404
```

This trace happens upon the first page load after deleting the cache:
<img width="1396" alt="Bildschirmfoto 2021-04-08 um 00 12 39" src="https://user-images.githubusercontent.com/533162/113941314-26e61680-97ff-11eb-95b3-c1b04c487cea.png">

What I don't understand yet is: why is it triggered on every page load. I can even remove the `trigger_deprecation()` after the container is built and the deprecation still shows up. Does the DebugClassloader somehow remember that deprecation? Is that compiled into the cached container?

**Comment by mbabker** [comment]
[`Symfony\Component\Debug\DebugClassLoader::checkAnnotations()`](https://github.com/symfony/symfony/blob/v4.4.21/src/Symfony/Component/Debug/DebugClassLoader.php#L225) and [`Symfony\Component\ErrorHandler\DebugClassLoader::checkAnnotations()`](https://github.com/symfony/symfony/blob/v4.4.21/src/Symfony/Component/ErrorHandler/DebugClassLoader.php#L408) both parse the class doc blocks and look for `@final`, `@deprecated`, and `@internal` annotations.  So even with the runtime `trigger_deprecation()` removed, the debug loader is going to catch the `@deprecated` annotation in the dev environment.

Also, assuming you have PagerfantaBundle installed, you don't need to add that particular mapping for FOSRestBundle; PagerfantaBundle ships event listeners which are enabled by default that converts `Pagerfanta\Exception\NotValidCurrentPageException` and `Pagerfanta\Exception\NotValidMaxPerPageException` instances to 404 errors already (and `Pagerfanta\Exception\OutOfRangeCurrentPageException` is a subclass of `NotValidCurrentPageException`).

**Comment by kevinpapst** [comment]
I migrated away from Pagerfanta bundle a longer time ago, as it was not maintained. I didn't even know that you took over the packages before yesterday.

The EventSubscriber was a very good hint, I added one to my app, removed the mapping from the FOS-Rest config and now the exception class is not loaded any longer and the deprecation gone. That fixes my immediate problem.  Not sure if I like the EventSubscriber over a simple configuration, but okay, works.

But there is still a point open that I'd like to raise: when I removed the `trigger_deprecation` (before cache warm-up) the log was gone. You are right: the DebugClassloader parses the code. BUT: the `@deprecation` annotation does not trigger an `E_USER_DEPRECATED`, because the Exception class is not used, but only loaded.
When I left the `trigger_deprecation` the log showed on every page load.

Maybe my use-case is a rare edge case, so you can safely ignore it ^^ especially as there is a workaround existing.

However you decide: I am grateful for your input, support and invested time. Thank you very much 😃

**Comment by kevinpapst** [comment]
Closing, because the deprecation could be fixed on my side.
