### ISSUE TITLE
Is it possible to create our own adapter and use it?

### ISSUE THREAD

**Issue by fd6130** [BabDev/Pagerfanta#26]
Hi, is it possible to create our own adapter and use it in pagerfanta?

For example, i want to use `Ds\Vector` instead of array but currently pagerfanta only have ArrayAdapter.

Thanks.

**Comment by mbabker** [comment]
Yes, you can create your own adapter.  You just need a class which implements `Pagerfanta\Adapter\AdapterInterface`, then you need to plug in whatever logic is needed for the two methods (`getNbResults` gives a count of the total (unpaginated) number of items in your list, and `getSlice` fetches the items for the current page in the list based on the given params) to work with whatever data source you'd like.  I've never used the ds extension, but based on the PHP docs, this could work:

```php
namespace App\Pagerfanta\Adapter;

use Ds\Vector;
use Pagerfanta\Adapter\AdapterInterface;

final class VectorAdapter implements AdapterInterface
{
    public function __construct(private Vector $vector) {}

    public function getNbResults(): int
    {
        return count($this->vector);
    }

    public function getSlice(int $offset, int $length): iterable
    {
        return $this->vector->slice($offset, $length);
    }
}
```
