### ISSUE TITLE
Add Template Parameter to AdapterInterface

### ISSUE THREAD

**Issue by MarkPedron** [BabDev/Pagerfanta#37]
The [QueryAdapter](/BabDev/Pagerfanta/tree/3.x/lib/Adapter/Doctrine/ORM/QueryAdapter.php#L13) has the queried type annotated as template parameter,
which allows more precise annotations (e.g. `@return QueryAdapter<MyEntity`).

It would be nice if the implemented [AdapterInterface](/BabDev/Pagerfanta/blob/3.x/lib/Core/Adapter/AdapterInterface.php) would have a template parameter as well.

**Comment by mbabker** [comment]
The annotations have been added in.  If you want to pull the latest dev build of the package(s) you're using before I tag things just to make sure it's not doing anything unexpected, that'd be great.  Otherwise, I'll tag releases later on in the week.

**Comment by MarkPedron** [comment]
Thank you for the immediate response! If I find something unexpected I will report.
