### ISSUE TITLE
Name of the package

### ISSUE THREAD

**Issue by stof** [BabDev/Pagerfanta#4]
Currently, this package has been submitted to packagist as `babdev/pagerfanta`.

If this because the official place to keep developing pagerfanta, maybe the `pagerfanta/pagerfanta` name could be transferred by the original maintainers.

One of the benefits of this transfer would be that you would then have the `pagerfanta/` namespace on Packagist, which would make things much better if splitting adapters to separate repos.

/cc @sampart

**Comment by stof** [comment]
the procedure for that would be for @mbabker to be added as a maintainer on the existing package. after than, the package can be un-abandoned on Packagist and the URL of the repository be edited.

**Comment by sampart** [comment]
That sounds great; I'll gladly do that.  @mbabker please can you confirm your Packagist username so I can add you?

**Comment by mbabker** [comment]
mbabker, if you can't find me by that username on the internet then I probably don't exist there 🤣

**Comment by sampart** [comment]
Haha, thanks. I've added you now. Feel free to make the changes @stof suggested.

And thank you Christophe for the suggestion.

**Comment by stof** [comment]
@mbabker I suggest changing the bundle to use the `pagerfanta/` vendor namespace for the package too.

**Comment by mbabker** [comment]
2.3.0 tagged changing this package back to `pagerfanta/pagerfanta` in Packagist, and 2.4.1 of the bundle tagged changing the dependency back.

I'll work on the bundle change later on, gotta get back to work now.
