### ISSUE TITLE
Please remove positive-int typehint from `Pagerfanta::setCurrentPage`

### ISSUE THREAD

**Issue by ruudk** [BabDev/Pagerfanta#40]
By adding the `positive-int` typehint to `Pagerfanta::setCurrentPage` it only becomes annoying for consumers of the library. I understand that it's nice to add this but I think it should be just asserted in the method.

Currently PHPStan reports 20 errors on our project:
```
Parameter #1 $currentPage of method Pagerfanta\Pagerfanta<Entity>::setCurrentPage() expects int<1, max>, int given.
```

I have to add this:
```php
Assert::greaterThanEq($page, 1);
```
in all 20 places where I call:
```
$pagerfanta->setCurrentPage($page);
```

Would it be possible to reconsider this?

**Comment by mbabker** [comment]
That's fair.  Done in https://github.com/BabDev/Pagerfanta/commit/1f1345306c2adca8c1cf857298aae677eb9e2a56

**Comment by ruudk** [comment]
Thank you 💙 could you please tag a new release ?

**Comment by mbabker** [comment]
Consider it done!
